[invoke-task] Automatically create the pulumi stack
DataDog/test-infra-definitions pull request #185
Opened 2023-06-21 09:09 UTC by pgimalac

What does this PR do?
---------------------
It automatically creates the pulumi stack in the invoke task if it didn't exist already.

Which scenarios this will impact?
-------------------
This is invoke task only so none.

Motivation
----------
Reducing the need for user interaction when using the invoke task.
I am writing a script which uses the invoke task to spawn multiple VM (each in their own stack) and I currently have to validate the creation of each stack manually.

Additional Notes
----------------
Listing the stacks and checking the names is the best way I could find to check if the stack exists, without any side-effect (`pulumi select` would work too but it has the side effect of selecting the stack).

2023-06-21 09:31 UTC, ogaca-dd approved these changes
LGTM. Thank you for the contribution.

2023-06-21 09:52 UTC, ogaca-dd approved these changes
LGTM

2023-06-21 11:21 UTC, vboulineau requested changes

2023-06-21 12:15 UTC, pgimalac commented on tasks/deploy.py
> +        stack_ls_out = subprocess.check_output(stack_ls_args)
@vboulineau should I wait for #184 to be merged or will you handle the conflicts ?

2023-06-26 15:15 UTC, pducolin approved these changes

2023-06-27 10:58 UTC, vboulineau approved these changes

2023-06-27 10:59 UTC, merged