[CONTINT-3600] Support k8s versions 1.28 and 1.29 in kind
DataDog/test-infra-definitions pull request #553
Opened 2024-01-10 10:55 UTC by adel121

What does this PR do?
---------------------

Support newer kubernetes versions (1.28 and 1.29) when creating kind clusters.

Which scenarios this will impact?
-------------------
kindvm

Motivation
----------
Being able to run E2E on newer k8s versions.

Additional Notes
----------------

2024-01-10 11:00 UTC, wdhif requested changes

2024-01-10 11:00 UTC, wdhif commented on components/kubernetes/kind_versions.go
> +		nodeImageVersion: "kindest/node:v1.29.0",
This should only be the tag, not the repository right?

2024-01-10 11:00 UTC, wdhif commented on components/kubernetes/kind_versions.go
> +		nodeImageVersion: "kindest/node:v1.28.0",
Also only the tag I suppose.

2024-01-10 14:21 UTC, AliDatadog approved these changes

2024-01-10 14:45 UTC, vboulineau reviewed
Aligning with other values

2024-01-10 14:45 UTC, vboulineau commented on components/kubernetes/kind_versions.go
> +		nodeImageVersion: "v1.28.0",
```suggestion
		nodeImageVersion: "v1.28.0@sha256:b7a4cad12c197af3ba43202d3efe03246b3f0793f162afb40a33c923952d5b31",
```

2024-01-10 14:45 UTC, vboulineau commented on components/kubernetes/kind_versions.go
> +		nodeImageVersion: "v1.29.0",
```suggestion
		nodeImageVersion: "v1.29.0@sha256:eaa1450915475849a73a9227b8f201df25e55e268e5d619312131292e324d570",
```

2024-01-11 09:26 UTC, adel121 commented
> Aligning with other values

Thanks @vboulineau 

I hadn't noticed that the digests were added [here](https://github.com/kubernetes-sigs/kind/releases#:~:text=Additional%20images%20built,v1.29.0%40sha256%3Aeaa1450915475849a73a9227b8f201df25e55e268e5d619312131292e324d570). I thought they will be added for the coming kind release.

2024-01-11 09:31 UTC, vboulineau approved these changes

2024-01-11 09:33 UTC, adel121 commented
/merge

2024-01-11 09:44 UTC, merged