e2e(kubernetes agent): Change WithHelmValues to not override everytime but to merge them
DataDog/test-infra-definitions pull request #717
Opened 2024-03-27 16:18 UTC by KevinFairise2

What does this PR do?
---------------------

Change the `WithHelmValues` optional args of `KubernetesAgent`. This way we can add several `WithHelmValues` args and they are merged automatically

Which scenarios this will impact?
-------------------

Motivation
----------

For `Kind` scenario we need to install the agent with some Helm values. Without this change you are not able to use `WithHelmValues` without specifying all the helm value needed internally to run on kind

Additional Notes
----------------

2024-03-28 13:07 UTC, vboulineau requested changes
Helm already does the merge, that's why it's a `AssetOrArchiveArray`. You simply append (to the end) newer values to the array.

2024-03-28 13:28 UTC, KevinFairise2 commented
> Helm already does the merge, that's why it's a `AssetOrArchiveArray`. You simply append (to the end) newer values to the array.

Oh that's nice. So I'd just need to replace 
```
p.HelmValues = pulumi.AssetOrArchiveArray{pulumi.NewStringAsset(values)}
```
by
```
p.HelmValues = append(p.HelmValues, pulumi.NewStringAsset(values))
```

Thanks for pointing it out!

2024-03-29 09:21 UTC, vboulineau approved these changes

2024-03-29 15:08 UTC, pducolin approved these changes

2024-03-29 16:07 UTC, KevinFairise2 commented
/merge

2024-03-29 16:34 UTC, merged